# Generated by Django 5.1 on 2024-09-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='saved_classes',
            field=models.ManyToManyField(blank=True, related_name='saved_by_teachers', to='myapp.class'),
        ),
    ]
