name: Pylint Django DRF Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pylint and pylint-django separately
        run: |
          pip install pylint pylint-django

      - name: Ensure __init__.py exists in drf_lib
        run: |
          touch drf_lib/__init__.py 

      - name: Set PYTHONPATH to include the project
        run: |
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run pylint with Django settings
        env:
          DJANGO_SETTINGS_MODULE: drf_lib.drf_lib.settings
        run: |
          pylint --load-plugins pylint_django drf_lib
